#!/bin/bash

# Assumes that noir v0.5.0 is installed

# Generate Board Verifier
echo "Generating Board Verifier"
cd circuits/board
nargo codegen-verifier
## Rename the contract from UltraVerifier to BoardVerifier
sed -i 's/contract UltraVerifier/contract BoardVerifier/g' contract/plonk_vk.sol
## Move the autogenerated verifier & rename the file
mv contract/plonk_vk.sol ../../contracts/BoardVerifier.sol
## Clean up the workspace
rm -rf contract

# Generate Shot Verifier
echo "Generating Board Verifier"
cd ../shot
nargo codegen-verifier
## Rename the contract from UltraVerifier to ShotVerifier
sed -i 's/contract UltraVerifier/contract ShotVerifier/g' contract/plonk_vk.sol
## Move the autogenerated verifier & rename the file
mv contract/plonk_vk.sol ../../contracts/ShotVerifier.sol
## Clean up the workspace
rm -rf contract

# Done
echo "Successfully generated UltraPlonk Verifier Contracts for Board and Shot circuits"
